from pathlib import Path
import json,hashlib,datetime
R=Path.cwd();O=R/'results/intervention_opportunity_discovery_v1';V=R/'results/prospective_temporal_state_cohort_v3'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
m=json.loads((V/'SCIENCE_RESULT_MANIFEST.json').read_text());assert sha(V/'SCIENCE_RESULT_MANIFEST.json')==(V/'SCIENCE_RESULT_MANIFEST.sha256').read_text().strip()
for n,h in m['files'].items():assert sha(V/n)==h,n
protocol={'version':1,'purpose':'EXPLORATORY_HYPOTHESIS_GENERATION_ONLY','frozen_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sealed_v3_manifest_sha256':sha(V/'SCIENCE_RESULT_MANIFEST.json'),
 'state_fields':['decision_level','trail_length','qhead','pending_queue_length','selected_action_count','conflicts','decisions','propagations','enqueues','heap_head_var','heap_head_activity_rank'],
 'action_fields':['clause_length','source','implied_literal','implied_var','antecedent_trail_positions','antecedent_min_trail_pos','antecedent_max_trail_pos','antecedent_mean_trail_pos','newest_antecedent_age','pending_antecedent_count','pending_antecedent_fraction','newest_antecedent_relative_to_qhead','all_antecedents_processed','implied_var_activity_hex','implied_var_activity','implied_var_activity_rank','implied_var_heap_rank','implied_var_in_heap','same_implied_literal_multiplicity','distinct_implied_literal_count','has_competing_implied_literals','max_variable_overlap','mean_variable_overlap','max_jaccard','mean_jaccard','watched_literals','watched_literal_trail_positions','watched_false_pending_count'],
 'definitions':{'trail_positions':'0-based in exact pre-intervention trail','antecedents':'clause literals other than implied; validate their negations are assigned in trail','newest_antecedent_age':'trail_length-1-max(antecedent positions)','pending_antecedent':'trail_pos >= qhead','relative_to_qhead':'max(antecedent positions)-qhead','activity':'exact hexadecimal binary64 from canonical var-ID list; rank is descending activity midrank, 1-based, ties preserved','heap_rank':'1-based native semantic pop order from qualified copy exporter, not raw heap layout; null when absent','overlap':'variable set intersections with each other frozen action; mean/max over all other actions; Jaccard=intersection/union','multiplicity':'only frozen tested action set, not full legal database','watches':'first two current clause literals from canonical clause line; binary symmetric; no full-db rescan','watch_pending':'assigned-false watched literal whose assignment trail_pos>=qhead','missing':'null, never 0; comparisons use per-field complete cases; report availability','historical_recovery':'Full authenticated pre-snapshot preferred. A same-parent fork baseline initial dequeue prefix of length trail_length-qhead exactly equals original pending queue under native FIFO; positions qhead+i are recoverable. Antecedents absent from this prefix are known processed but their exact positions are unavailable. Never treat matching counters as cross-run exact identity.'},
 'bounded_predicates':['pending_antecedent_count > 0','all_antecedents_processed','distinct_implied_literal_count > 1','same_implied_literal_multiplicity > 1','pending_queue_length > 0','newest_antecedent_relative_to_qhead == 0','newest_antecedent_relative_to_qhead > 0','watched_false_pending_count > 0'],
 'permitted_conjunctions':[['pending_antecedent_count > 0','distinct_implied_literal_count > 1'],['newest_antecedent_relative_to_qhead == 0','distinct_implied_literal_count > 1']],
 'candidate_rule_scope':'exists frozen action satisfying one listed predicate or one of the two listed conjunctions; report every tested predicate, no more mining','continuous_features':'distributions and ranks only, no cutoff optimization',
 'candidate_requirement':'multiple distinct auditable positive states, representation across targets, all included positive-state coverage, actual v3 inert-state exclusion, mechanism interpretation; no promotion',
 'historical_scope':'same-run exact fork identity is valid historical experimental evidence; no independent replay via legacy hashes. Partial field alignment must be explicitly marked.',
 'exclusions':['temporal_v1','temporal_v2','old_qualification_invalid_identity','unverified_or_unalignable_history'],'no_interventions':True}
p=O/'OPPORTUNITY_FEATURE_PROTOCOL_V1.json'
with p.open('x') as f:json.dump(protocol,f,indent=2);f.write('\n')
(O/'OPPORTUNITY_FEATURE_PROTOCOL_V1.sha256').write_text(sha(p)+'\n')
print('SEALED_V3_VERIFIED; OPPORTUNITY_FEATURE_FAMILY_FROZEN')
