import json,subprocess,hashlib,shutil
from pathlib import Path
ROOT=Path.cwd();O=ROOT/'results/opportunity_generation_v2';B=Path('/tmp/satfinding-v2-collector');cnf=ROOT/'results/full_propagation_frontier_observer_v2/inputs/T10_qualification.cnf';state=ROOT/'results/fresh_heuristic_causal_cohort_v1/cases/T10M3';
base=json.loads((state/'checkpoint/state.json').read_text()); sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
runs=[]
for tag in ['OFF','ON1','ON2']:
 d=Path('/tmp')/('v2qual_'+tag);shutil.rmtree(d,ignore_errors=True);d.mkdir();(d/'plan').write_text('6 1 1 1 800 800\n');proof=d/'proof.drup';z=subprocess.run([str(B),str(cnf),str(proof),str(d),str(d/'plan')],capture_output=True,text=True);x=json.loads((d/'S1/actions.json').read_text());q=subprocess.run([str(ROOT/'execution_pipeline_v1/native/proof-checker'),str(cnf),str(proof)],capture_output=True,text=True);runs.append({'tag':tag,'exit':z.returncode,'status':z.stdout.strip(),'legal_count':x['legal_count'],'all_actions_count':len(x.get('all_actions',[])),'metadata_complete':sum(all(k in a for k in ['id','literal','source','clause']) and a['literal'] in a['clause'] for a in x.get('all_actions',[])),'proof_verified':q.returncode==0 and 'VERIFIED' in q.stdout,'actions_sha256':sha(d/'S1/actions.json'),'checkpoint_sha256':sha(d/'S1/checkpoint.json')})
(O/'NONPERTURBATION_QUALIFICATION.json').write_text(json.dumps({'runs':runs,'OFF_ON_equivalent':False,'reason':'COLLECTOR binary has no telemetry OFF/ON mode; runs are repeated collector executions only.'},indent=2)+'\n')
# deterministic and metadata
(O/'COLLECTOR_DETERMINISM_QUALIFICATION.json').write_text(json.dumps({'run1_actions_sha256':runs[1]['actions_sha256'],'run2_actions_sha256':runs[2]['actions_sha256'],'exact_stable':runs[1]['actions_sha256']==runs[2]['actions_sha256']},indent=2)+'\n')
(O/'ALL_ACTION_METADATA_QUALIFICATION.json').write_text(json.dumps({'checked':runs[1]['all_actions_count'],'metadata_complete':runs[1]['metadata_complete'],'pass':runs[1]['metadata_complete']==runs[1]['all_actions_count']},indent=2)+'\n')
(O/'COLLECTOR_QUALIFICATION_PROOFS.json').write_text(json.dumps({'routes':runs,'verified':sum(r['proof_verified'] for r in runs),'total':len(runs)},indent=2)+'\n')
(O/'TIMING_CORRECTNESS_QUALIFICATION.json').write_text(json.dumps({'independently_verified':0,'total':runs[1]['all_actions_count'],'pass':False,'reason':'Independent baseline telemetry timing comparator is not available from COLLECTOR output; all_actions inventory has no native timing fields.'},indent=2)+'\n')
q={'COLLECTOR_QUALIFIED':False,'protocol_sha256':'f9f0ad327b059d5298f18d7b979f9752916b2a9b3fef0e08a96a0168b42be8ed','source_commit':'1f0acbddacdf26860221f5218071ca5a8223e389','binary_sha256':sha(B),'input_sha256':sha(cnf),'checkpoint_sha256':sha(state/'checkpoint/state.json'),'gates':{'BUILD_VERIFIED':True,'FULL_ACTION_INVENTORY':runs[1]['all_actions_count']==runs[1]['legal_count'],'METADATA_COMPLETE':runs[1]['metadata_complete']==runs[1]['all_actions_count'],'DETERMINISM_PASS':runs[1]['actions_sha256']==runs[2]['actions_sha256'],'NONPERTURBATION_PASS':False,'TIMING_CORRECTNESS_PASS':False,'PROOFS_VERIFIED':sum(r['proof_verified'] for r in runs)==3},'failed_gate':'NONPERTURBATION_PASS and TIMING_CORRECTNESS_PASS','scientific_routes_consumed':0,'qualification_states':['T10M3/rank5']}
(O/'OPPORTUNITY_V2_COLLECTOR_QUALIFICATION.json').write_text(json.dumps(q,indent=2)+'\n')
print(json.dumps(q,indent=2))
